### ISSUE TITLE
Import from URL instructions dont work

### ISSUE THREAD

**Issue by tseemann** [sepsis-omics/tutorials#11]
Importing the Data.tar.gz as described doesn't seem to work. 

It never loads in.

Is this a Galaxy bug?

@slugger70

**Comment by Slugger70** [comment]
How big is the file data.tgz? If it's bigger than 2GB then you can't use the http instructions to upload it and it has to be done by ftp.. This is a http limitation. nothing to do with Galaxy...

You might need to rethink the way data is loaded.. Tutorial data sets should be small! It takes a long time to get that right!

**Comment by tseemann** [comment]
It's only 35 **Mb** 

http://sepsis-omics.github.io/tutorials/modules/data-dna/Data.tar.gz 

```
tar ztf Data.tar.gz
datasets/mutant_R1.fastq_1.fastqsanger
datasets/mutant_R2.fastq_2.fastqsanger
datasets/wildtype.gff_3.gff3
datasets/wildtype.fna_4.fasta
datasets/wildtype.gbk_5.genbank
history_attrs.txt
datasets_attrs.txt
datasets_attrs.txt.provenance
jobs_attrs.txt
```

**Comment by Slugger70** [comment]
Which machine are you trying to load it into?

**Comment by tseemann** [comment]
gcc

**Comment by AnnaSyme** [comment]
Appears in history it but has 0 b and only 1 file is listed (so it's not really loaded).

**Comment by Slugger70** [comment]
I think it's got something to do with a python command io.rename. It won't move files across filesystems.. I have to shift the upload_store from transient storage to volume..

**Comment by AnnaSyme** [comment]
Just confirming: works on sepsis machine but not GCC.

**Comment by AnnaSyme** [comment]
I think this issue is fixed. Closed.
